server:
  port: 8080
  #ssl:
    #    证书路径
   # key-store: classpath:www.jsdai.club.jks
   # keyStoreType: JKS
   # key-alias: tomcat
    #    配置密码，就是在生成证书的时候输入的密码
  #  key-store-password: jsdai123

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/jsdai?useSSL=false
    username: root
    #password: dzq@1234
    password: Jsdai!@#321
    driver-class-name: com.mysql.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 5
      maximum-pool-size: 20
      auto-commit: true
      idle-timeout: 30000
      max-lifetime: 1800000
      connection-timeout: 30000
#    type: com.alibaba.druid.pool.DruidDataSource
#    maxActive: 20
#    initialSize: 1

mybatis:
  mapper-locations: classpath:mapping/*Mapper.xml
  type-aliases-package: com.jsdai.jsdaimanage.bean

#pagehelper分页插件
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
#logging:
#  level:
#    com.jsdai.jsdaimanage.dao: info

jpush:
  appKey: ac03060d4343cfdc3e3a0d3d
  masterSecret: b8addc34cc18cfa42e2fa06d